# Generated by Django 6.0.6 on 2026-07-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_feedback',
            fields=[
                ('form_id', models.AutoField(primary_key=True, serialize=False)),
                ('satisfaction_level', models.IntegerField(blank=True, null=True)),
                ('recommend_others', models.IntegerField(blank=True, null=True)),
                ('product_quality', models.IntegerField(blank=True, null=True)),
                ('ease_of_use', models.IntegerField(blank=True, null=True)),
                ('customer_support', models.IntegerField(blank=True, null=True)),
                ('value_for_money', models.IntegerField(blank=True, null=True)),
                ('delivery_speed', models.IntegerField(blank=True, null=True)),
                ('product_service', models.CharField(blank=True, max_length=255, null=True)),
                ('product_improvement', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_comments', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
