# Generated by Django 6.0.6 on 2026-07-29 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_add_feedbacklink_and_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_feedback',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='feedback.organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedbacklink',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_links', to='feedback.organization'),
        ),
    ]
