# Generated by Django 6.0.6 on 2026-07-29 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_add_initial_organizations'),
        ('feedback', '0003_alter_customer_feedback_organization_and_more'),
    ]

    operations = [
    ]
