# Generated by Django 6.0.6 on 2026-07-29 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_feedback_extend_fields'),
        ('feedback', '0004_merge_20260729_0659'),
    ]

    operations = [
    ]
