# Generated by Django 6.0.6 on 2026-08-03 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_merge_20260729_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_feedback',
            name='responses',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacklink',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_links', to='feedback.organization'),
        ),
        migrations.CreateModel(
            name='FormQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('help_text', models.CharField(blank=True, max_length=512, null=True)),
                ('question_type', models.CharField(choices=[('csat', 'CSAT'), ('nps', 'NPS'), ('rating_scale', 'Rating scale'), ('single_choice', 'Single choice'), ('multi_choice', 'Multiple choice'), ('yes_no', 'Yes / No'), ('short_text', 'Short text'), ('long_text', 'Long text')], max_length=32)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('required', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_questions', to='feedback.organization')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
